token: 这里是HA的token
# 要监听蓝牙MAC地址
mac:
  - B4:C4:FC:66:A6:F0
# 监听按键
key:
  71:
    # 7
    service: light.toggle
    data:
      entity_id: light.xiaomi_philips_light
  72:
    # 8
    service: light.toggle
    data:
      entity_id: light.cai_deng
  73:
    # 9
    service: ha_cloud_music.load
    data:
      id: 19723756
      type: playlist
    long_service: ha_cloud_music.load
    long_data:
      id: 3779629
      type: playlist
  74:
    # -
    service: media_player.volume_down
    data:
      entity_id: media_player.ha_cloud_music
  75:
    # 4
    service: switch.toggle
    data:
      entity_id: switch.dian_shi
  76:
    # 5
    service: switch.toggle
    data:
      entity_id: switch.tian_mao_he_zi
  77:
    # 6
    service: ha_cloud_music.load
    data:
      id: 2884035
      type: playlist
    long_service: ha_cloud_music.load
    long_data:
      id: 3778678
      type: playlist
  78:
    # +
    service: media_player.volume_up
    data:
      entity_id: media_player.ha_cloud_music
  79:
    # 1
    service: media_player.media_previous_track
    data:
      entity_id: media_player.ha_cloud_music
  80:
    # 2
    service: media_player.media_play_pause
    data:
      entity_id: media_player.ha_cloud_music
  81:
    # 3
    service: media_player.media_next_track
    data:
      entity_id: media_player.ha_cloud_music
  96:
    # 回车
    service: automation.trigger
    data:
      entity_id: automation.gong_jiao_dao_zhan_bo_bao