load:
  description: 加载网易云音乐歌单音乐列表
  fields:
    id:
      description: 参数介绍【https://github.com/shaonianzhentan/ha_cloud_music/tree/master/custom_components/ha_cloud_music】
      example: '258244'
    type:
      description: 网易歌单(playlist)、网易电台(djradio)、喜马拉雅专辑(ximalaya)
      example: 'ximalaya'
    index:
      description: 要从第几首开始播放（如果超过列表总数量则从第1首开始播放）
      example: '1'
play_mode:
  description: 设置播放模式
  fields:
    mode:
      description: 播放模式（0：列表循环，1：顺序播放，2：随机播放，3：单曲循环）
      example: '1'
tts:
  description: 文字转语音
  fields:
    message:
      description: 要播放的文字（目前只支持内置VLC）
      example: '支持时间格式占位符，%Y年%m月%d日 %H:%MM:%S天气真不错'
notify:
  description: QQ邮件通知提醒
  fields:
    title:
      description: 【必填】邮件标题
      example: '邮件标题'
    message:
      description: 【必填】要提醒的文字（可以为HTML格式）
      example: '<b>这是一条提醒</b>'
    action:
      description: 【非必填】要执行的脚本或自动化实体
      example: 'automation.gong_jiao_dao_zhan_bo_bao'