- id: '1571917340608'
  alias: 欢迎回家
  trigger:
  - entity_id: device_tracker.b4_c4_fc_66_a6_f0
    from: not_home
    platform: state
    to: home
  - event: sunset
    platform: sun
  condition:
  - condition: state
    entity_id: light.xiaomi_philips_light
    state: 'off'
  - condition: state
    entity_id: light.cai_deng
    state: 'off'
  action:
  - data_template:
      message: 检测到{{ now() }}有人回来了
      title: 回家检测
    service: persistent_notification.create
  - data:
      entity_id: automation.huan_ying_hui_jia
    service: automation.turn_off
  - data:
      entity_id: light.cai_deng
    service: light.turn_on
  - data:
      entity_id: light.xiaomi_philips_light
    service: light.turn_on

- id: '1573571617255'
  alias: 离家警戒
  description: 晚上6点的时候，如果我不在家，则开启检测回家模式
  trigger:
  - hours: '18'
    minutes: '0'
    platform: time_pattern
    seconds: '0'
  condition:
  - condition: state
    entity_id: device_tracker.b4_c4_fc_66_a6_f0
    state: not_home
  action:
  - data:
      entity_id: automation.huan_ying_hui_jia
    service: automation.turn_on